"""empty message

Revision ID: 3d27be64ebb9
Revises: 93bc89d93405
Create Date: 2020-02-27 18:55:43.477666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d27be64ebb9'
down_revision = '93bc89d93405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR(length=40)), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###
