"""empty message

Revision ID: 3e80f4e6595b
Revises: fa82d1d2f912
Create Date: 2020-02-23 11:12:01.751800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e80f4e6595b'
down_revision = 'fa82d1d2f912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.Date(), nullable=True))
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
