"""empty message

Revision ID: 73d623dd5556
Revises: 3e80f4e6595b
Create Date: 2020-02-23 11:23:28.132494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d623dd5556'
down_revision = '3e80f4e6595b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('started_time', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'started_time')
    # ### end Alembic commands ###
